### ISSUE TITLE
KL_loss becomes zero after several hundreds of steps ?

### ISSUE THREAD

**Issue by xiaoyangnihao** [yanggeng1995/vae_tacotron#10]
I train my vae model with your code with Blizzard2013, the kl_loss seems to become zero after serveal hundreds of steps. I try to change the vae weight strategy, but it seems useless.  @yanggeng1995, @rishikksh20  Any advices to avoid the KL_loss become zero ?

**Comment by xiaoyangnihao** [comment]
![issue](https://user-images.githubusercontent.com/14233490/84486101-7c30c480-accf-11ea-9674-45df3844eb2c.png)

**Comment by rishikksh20** [comment]
@xiaoyangnihao Actually that is the main problem we all are facing, actually that is the problem with VAE models. Better strategy the start training again with two to three checkpoint before. For example if you get 0 at 30000 step then re-start training with any checkpoint from 25k to 27k.

**Comment by xiaoyangnihao** [comment]
> @xiaoyangnihao Actually that is the main problem we all are facing, actually that is the problem with VAE models. Better strategy the start training again with two to three checkpoint before. For example if you get 0 at 30000 step then re-start training with any checkpoint from 25k to 27k.

Thanks for your quick response. But in my case, it starts to drop to zeros only in two hundreds stpes, which is weired. Have you evered faced this phenomenon ？

**Comment by xiaoyangnihao** [comment]
@rishikksh20 Thanks for your quick response. But in my case, the kl_loss starts to drop to zero at the begining of my training, which is so weired. Have your ever faces this phenomenon?

**Comment by rishikksh20** [comment]
@xiaoyangnihao No I haven't faced such issue, you can try my repo : https://github.com/rishikksh20/vae_tacotron2
