### ISSUE TITLE
Blizzard2013 368K training results.Will vae-tacotron2 get better results?

### ISSUE THREAD

**Issue by xieyuankun** [yanggeng1995/vae_tacotron#7]
I trained the model 368k with Blizzard2013 and the here is the result (Parallel transfer） 
[https://drive.google.com/drive/folders/12dBWg883S1VXQ0jEzJ7Lcz1bxI3lI_2t](url)
You can hear that 118 119 is well but 120 has less prosody.
These audios have metal tones because of the Grrifin-LIM.I will use vocoder such as wavenet or wavernn to improve audio quality.
I think training less than 200k times it cant train prosody. The model's mission within 200k times is training a good alignment .More than 200K it will begin to train prosody according to the reference.
368k isn‘t enough to train a good prosody model.  I think the number of training needs to be greater. I will keep training.
By the way if i change the model into tacotron2.Will it produce better results or simliar results like tacotron1 ?Does anyone trained model as good as the paper?

**Comment by yanggeng1995** [comment]
The parameters of the paper are set on the model of tacotron2, may be you
can try it on tracotron2, by the way, you should pay attention to the ki
loss during training  to prevent it from crashing.

Xie Yuan Kun <notifications@github.com> 于2019年9月20日周五 上午11:01写道：

**Comment by xiaoyangnihao** [comment]
@yanggeng1995 @xieyuankun Does datasets/blizzard2013.py useful ? Now I am a little confused how to preprocess Blizzard 2013 datasets.
